# Generated by Django 5.2.3 on 2025-06-19 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Policial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=150)),
                ("nome_guerra", models.CharField(max_length=150)),
                ("nome_mae", models.CharField(max_length=150)),
                ("nome_pai", models.CharField(blank=True, max_length=150, null=True)),
                ("data_nascimento", models.DateField()),
                ("matricula", models.CharField(max_length=20, unique=True)),
                ("identidade_militar", models.CharField(max_length=20, unique=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                (
                    "posto_graduacao",
                    models.CharField(
                        choices=[
                            ("SD", "Soldado"),
                            ("CB", "Cabo"),
                            ("SGT", "Sargento"),
                            ("ST", "Subtenente"),
                            ("ASP", "Aspirante"),
                            ("TEN", "Tenente"),
                            ("CAP", "Capitão"),
                            ("MAJ", "Major"),
                            ("TC", "Tenente-Coronel"),
                            ("CEL", "Coronel"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")], max_length=1
                    ),
                ),
                (
                    "tipagem_sanguinea",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("AB", "AB"), ("O", "O")],
                        max_length=3,
                    ),
                ),
                (
                    "fator_rh",
                    models.CharField(
                        choices=[("+", "Positivo"), ("-", "Negativo")], max_length=1
                    ),
                ),
                ("data_ingresso", models.DateField()),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_policiais/"
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        choices=[
                            ("PATRULHEIRO", "Patrulheiro"),
                            ("MOTORISTA", "Motorista"),
                            ("ENCARREGADO", "Encarregado"),
                            ("CHEFE", "Chefe"),
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("COORDENADOR", "Coordenador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("endereco", models.TextField()),
                ("telefone", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
