# Generated by Django 5.2.3 on 2025-06-19 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agressor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=150)),
                ("identidade", models.CharField(max_length=20)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nascimento", models.DateField()),
                ("endereco", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_agressores/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guarnicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viatura",
                    models.CharField(
                        choices=[
                            ("VTR-01", "Viatura 01"),
                            ("VTR-02", "Viatura 02"),
                            ("VTR-03", "Viatura 03"),
                        ],
                        max_length=10,
                    ),
                ),
                ("inicio_servico", models.DateTimeField()),
                ("fim_servico", models.DateTimeField(blank=True, null=True)),
                ("km_inicial", models.PositiveIntegerField()),
                ("km_final", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Assistida",
            fields=[
                (
                    "numero_processo",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_assistidas/"
                    ),
                ),
                ("nome_completo", models.CharField(max_length=150)),
                ("nome_mae", models.CharField(max_length=150)),
                ("nome_pai", models.CharField(blank=True, max_length=150, null=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nascimento", models.DateField()),
                ("identidade", models.CharField(max_length=20)),
                ("endereco", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("data_visita", models.DateField()),
                ("validade_processo", models.DateField()),
                (
                    "agressor_citado",
                    models.CharField(
                        choices=[("SIM", "Sim"), ("NAO", "Não")], max_length=3
                    ),
                ),
                ("ultima_visita", models.DateField()),
                ("ocorrencia", models.TextField(blank=True, null=True)),
                ("cancelar_atendimento", models.BooleanField(default=False)),
                (
                    "agressor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_base.agressor",
                    ),
                ),
                (
                    "guarnicao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_base.guarnicao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuarnicaoIntegrante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        choices=[
                            ("COMANDANTE", "Comandante"),
                            ("MOTORISTA", "Motorista"),
                            ("PATRULHEIRO", "Patrulheiro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "guarnicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrantes",
                        to="api_base.guarnicao",
                    ),
                ),
                (
                    "policial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_base.policial",
                    ),
                ),
            ],
        ),
    ]
